diff --git a/2.3/Dockerfile b/2.3/Dockerfile
index 2320f7f..26b1ddd 100644
--- a/2.3/Dockerfile
+++ b/2.3/Dockerfile
@@ -17,2 +17 @@ ENV RUBYGEMS_VERSION 2.6.4
-RUN set -ex \
-	&& buildDeps=' \
+ENV buildDeps=' \
@@ -22,2 +21,3 @@ RUN set -ex \
-	' \
-	&& apt-get update \
+	'
+RUN set -ex \
+    && apt-get update \
@@ -34,2 +34,2 @@ RUN set -ex \
-	&& ./configure --disable-install-doc \
-	&& make -j"$(nproc)" \
+	&& ./configure --disable-install-doc
+ONBUILD RUN cd /usr/src/ruby && make -j"$(nproc)" \
@@ -39 +39,2 @@ RUN set -ex \
-	&& rm -r /usr/src/ruby
+	&& rm -r /usr/src/ruby \
+	&& unset buildDeps
@@ -43 +44 @@ ENV BUNDLER_VERSION 1.12.4
-RUN gem install bundler --version "$BUNDLER_VERSION"
+ONBUILD RUN gem install bundler --version "$BUNDLER_VERSION"
